### ISSUE TITLE
Deleting a user from admin area

### ISSUE THREAD

**Issue by andreas22** [intrip/laravel-authentication-acl#10]
The following issue arise when developing different modules in admin and linking users to the new modules in database tables. For example I have the following table, which it has as a foreign key user. When I have records created that are linked to a specified user and I try to delete that user I get an error 500 
'SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails
CREATE TABLE `data` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` text COLLATE utf8_unicode_ci NOT NULL,
  `created_at` datetime NOT NULL,
  `created_by` int(10) unsigned NOT NULL
  PRIMARY KEY (`id`),
  KEY `data_created_by_foreign` (`created_by`), 
  CONSTRAINT `data_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
) 

I dont know if in laravel you can have triggers at database levels, so I can bind a method to the trigger before deleting a user but this triggers would be best to be on application level, ie action delete user, before_delete, after_delete.

In addition to this I would suggest when deleting a user to use soft delete that way nothing will be affected and the flow will continue as normal.

**Comment by intrip** [comment]
Your problem is related to to database integrity check. Assuming that you're using mysql as DBMS you could either change your constraint definition to something like this: 
CONSTRAINT data_created_by_foreign FOREIGN KEY (created_by) REFERENCES users (id), ON DELETE CASCADE ON UPDATE CASCADE,
Or you could also temporary stop integrity check with Jacopo\Authentication\Helpers\DbHelper::stopForeignKeysCheck();
Remember to enable it back. 
You could also handle that manually in you're code overriding eloquent delete() method and deleting the user associated to the data before deleting the data table.
I hope is clear enough.

**Comment by andreas22** [comment]
I believe that none of the above solutions will be ok.

The 1st DELETE CASCADE ON UPDATE CASCADE, means that when a user is deleted to also delete my records in the other tables, correct me if i am wrong.

2nd stopForeignKeysCheck() if i understand correctly to set the foreign keys check off, delete the user and then put it back to on, that will have as a result the user deleted and the records linked to be orphans,

3rd the issue is when I delete the user first and not the other way around

Instead of throwing an exception 500, to handle the exception and print a meaningful message for example that the user has records associate with him and needs to be deleted first or reassigned in order to proceed  :)

**Comment by intrip** [comment]
Doest any of mysql cascade operations doesn't solve the problem? take a look here: http://stackoverflow.com/questions/1027656/what-is-mysqls-default-on-delete-behavior. Otherwise could you please explaing me more your problem? Thanks. :smile:
