### ISSUE TITLE
Login dosn't work correct with 5.2

### ISSUE THREAD

**Issue by Silvio8** [intrip/laravel-authentication-acl#113]
After installing the last version for laravel 5.2 i tried to login with admin@admin.com.
That works. I will be redirected to the given url. If I use the wrong password than not.

But if I try to show information about the auth user it doesn't work.
if I write:
$authentication = \App::make('authenticator');
$ben=$authentication->getLoggedUser();
print_r($ben);
it shows nothing

But if I write this before to login manually than it works:
$i=$authentication->loginById(1,false);

Where is the problem?
Please help.

**Comment by intrip** [comment]
In order to see the current user the route need to have the 'admin_logged' filter middleware.

**Comment by gamingumar** [comment]
Hi, I am also having the same problem, i want to do this for the client user, how can i see the currently logged in user

**Comment by elysiopires** [comment]
I'm having the same problem...
I migrated my project from version 5.1 to 5.2 updated all my routes to middleware instead of filter "before" and updated my kernel with the middlewares... but login is not working...

After login I got null on App::make('Authenticator')->getLoggedUser() and false on App::make('authenticator')->check()

I follow all the instructions, change the composer.json version, then run composer update then composer install
Altered the Kernel.php adding the middlewares and no success...

I can login in /admin/login and see all the users dashboards, but when I try to use any method of App::make('authenticator') its return null or false.

Please Help...
