### ISSUE TITLE
URL::route not working

### ISSUE THREAD

**Issue by rbejjani** [intrip/laravel-authentication-acl#40]
Hey I am new to Laravel, I need to add more features for the admin when he's logged, I want him to add data to the database, when I try to change the route in menu.php to the page that I want it stops working.

"route" => "latestnews",
"link" => URL::route('pageedit.latestnews'),

**Comment by intrip** [comment]
You need to create that named route aswell in your routes.php: http://laravel.com/docs/4.2/routing#named-routes

**Comment by rbejjani** [comment]
Thank you for your quick reply!
But why when I login on mysite/login it redirect me to my home page, I want it to redirect me to another page

**Comment by TolotraRam** [comment]
Hi, 
you can override the file on /vendor/jacopo/laravel-authentication-acl/src/controllers/AuthController.php go to the method postClientLogin and edit the redirection after success login.
But it's not the proper way to do that cause you will loose your changes after a composer update.
@intrip is it possible to fire a event in place of redirecting so that everyone can listen to this event and redirect where he wants?

**Comment by intrip** [comment]
Firing and event is not a good solution in this case. I'll put that redirect route in a configuration file so that you can easy change it. Will give you a feedback when i'm done.

**Comment by TolotraRam** [comment]
Nice !
but i wonder is there a good solution to override all controller cause i didn't see any php artisan controller::publish ?

**Comment by intrip** [comment]
Laravel doesn't allow you that.

**Comment by rbejjani** [comment]
Thank you very much for your help it worked!!

**Comment by intrip** [comment]
You're welcome! Closing issue then.

**Comment by TolotraRam** [comment]
Sorry but have you already put the redirection in the config file?

**Comment by intrip** [comment]
I pushed that to version 1.2.4 con config.php file
